name: Manual FTP Pull

on:
  workflow_dispatch:

jobs:
  ftp-pull:
    name: Pull from FTP and Commit to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Pull files from FTP server (htdocs)
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        mkdir -p htdocs
        lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --delete --only-newer /htdocs/ htdocs/
        "

    - name: Check for changes
      run: |
        if [[ -n $(git status --porcelain htdocs) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Print Git Remote URL
      run: git remote -v

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Debug GitHub Token Authentication
      run: |
        echo "GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}"
        echo "Testing GitHub Token Authentication..."
        curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" https://api.github.com/user

    - name: Update Remote URL to use PAT
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git
        git remote -v

    - name: Push changes to GitHub
      run: |
        git add htdocs/*
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync htdocs with FTP server"
          git push origin main
        else
          echo "No changes to commit."
        fi
