name: Manual FTP Pull

on:
  workflow_dispatch:

jobs:
  ftp-pull:
    name: Pull from FTP and Commit to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Pull files from FTP server (htdocs)
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        mkdir -p htdocs
        lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --delete --only-newer /htdocs/ htdocs/
        "

    - name: Remove extra files from GitHub repo not present on FTP server
      run: |
        # Get the list of deleted files and remove them if there are any
        deleted_files=$(git ls-files --deleted)
        if [[ -n "$deleted_files" ]]; then
          echo "$deleted_files" | xargs git rm
        else
          echo "No files to remove from Git repository."
        fi

    - name: Check for changes in htdocs directory
      run: |
        # Check if there are any changes in the 'htdocs' directory after pulling from FTP
        if [[ -n $(git status --porcelain htdocs) ]]; then
          echo "Changes detected in htdocs. Preparing to push."
        else
          echo "No changes detected in htdocs. Exiting."
          exit 0
        fi

    - name: Push changes to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Configure Git user for commit
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Stage all changes in the 'htdocs' directory
        git add htdocs/*

        # Commit changes if there are any
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync htdocs with FTP server"
          git push origin main
        else
          echo "No changes to commit."
        fi
