name: Manual FTP Pull

on:
  workflow_dispatch:

jobs:
  ftp-pull:
    name: Pull from FTP and Commit to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Pull files from FTP server and sync with Git repository
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        # Ensure we are in the GitHub Actions workspace
        cd $GITHUB_WORKSPACE
        
        # Use lftp to mirror the FTP server's 'htdocs' directory to the root directory of the Git repository
        lftp -c "
          set ftp:ssl-force false;
          set ftp:ssl-protect-data false;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --delete --only-newer /htdocs/ .
        "

        # Remove any files from the Git repo that are not on the FTP server
        git ls-files --deleted | xargs -r git rm

    - name: Check for changes
      run: |
        # Check if there are changes in the repository
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Push changes to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Configure Git user for commit
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

        # Add all changes to git
        git add -A

        # Commit and push changes if there are any
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync htdocs with FTP server"
          git push origin main
        else
          echo "No changes to commit."
        fi
