name: Manual FTP Pull

on:
  workflow_dispatch:

jobs:
  ftp-pull:
    name: Pull from FTP and Commit to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Pull files from FTP server (htdocs)
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --delete --only-newer /htdocs/ htdocs/
        "
    - name: Check for changes
      run: |
        if [[ -n $(git status --porcelain htdocs) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi
    - name: Push changes to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git
        git add htdocs/*
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync htdocs with FTP server"
          git push origin main
        else
          echo "No changes to commit."
        fi
