name: FTP Pull and Sync to Git Root

on:
  workflow_dispatch:

jobs:
  ftp-pull:
    name: Pull from FTP and Sync to GitHub Repository Root
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        ref: main  # Checkout the main branch of your repository

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Pull files from FTP server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        # Create a temporary directory to store FTP files
        mkdir -p /tmp/ftp-files

        # Use lftp to mirror the FTP directory to the temporary directory
        lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --delete --only-newer /htdocs/ /tmp/ftp-files/
        "

    - name: Sync files to repository root
      run: |
        # Move all files from the temporary directory to the repository root
        rsync -av --delete /tmp/ftp-files/ ./

    - name: Check for changes
      run: |
        # Check if there are changes in the repository
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Sync htdocs with FTP server"
        git push origin main
