name: Manual FTP Pull

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ftp-pull:
    name: Pull from FTP and Commit to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main  # Ensure we are checking out the main branch

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: List local files with timestamps and sizes
      run: |
        find . -type f -exec stat --format='%Y %s %n' {} \; | sort > local_files.txt

    - name: List remote files with timestamps and sizes
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --list-only --verbose --exclude .git/ --exclude .github/ /htdocs/ ./remote_files/
        "
        # Generate file list from FTP
        find ./remote_files -type f -exec stat --format='%Y %s %n' {} \; | sort > remote_files.txt

    - name: Compare file lists and sync modified files
      run: |
        # Compare local and remote file lists
        diff local_files.txt remote_files.txt > file_diff.txt
        
        if [ -s file_diff.txt ]; then
          echo "Differences found. Syncing modified files."
          
          # Sync modified files from FTP
          lftp -c "
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            set ssl:verify-certificate no;
            open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
            mirror --verbose --delete --only-newer --exclude .git/ --exclude .github/ /htdocs/ ./
          "
          
          # Remove temp files
          rm local_files.txt remote_files.txt file_diff.txt
        else
          echo "No differences found. Exiting."
        fi

    - name: Verify .git directory exists
      run: |
        if [ ! -d .git ]; then
          echo "Error: .git directory is missing. Reinitializing Git."
          git init
          git remote add origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git
          git fetch origin
          git checkout main
        else
          echo ".git directory exists."
        fi

    - name: Check for changes
      run: |
        # Check for changes in the repository root
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Push changes to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Updated secret name
      run: |
        # Configure Git
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"

        # Stage all changes including deletions
        git add -A

        # Commit changes if there are any
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync root with FTP server"
          git push origin main
        else
          echo "No changes to commit."
        fi
