name: Manual FTP Pull

on:
  workflow_dispatch:

jobs:
  ftp-pull:
    name: Pull from FTP and Commit to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Pull files from FTP server (htdocs)
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        # Ensure you are in the GitHub Actions workspace, which is a git repository
        cd $GITHUB_WORKSPACE

        # Use lftp to mirror the FTP htdocs directory to the root directory of the Git repository
        lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --delete --only-newer /htdocs/ .
        "

    - name: Remove extra files from GitHub repo not present on FTP server
      run: |
        # Ensure you are in the GitHub Actions workspace, which is a git repository
        cd $GITHUB_WORKSPACE

        # Get the list of files that have been deleted from the FTP server but are still in the Git repository
        deleted_files=$(git ls-files --deleted)
        
        # If there are deleted files, remove them from the Git repository
        if [[ -n "$deleted_files" ]]; then
          echo "$deleted_files" | xargs git rm
        else
          echo "No files to remove from Git repository."
        fi

    - name: Check for changes in the root directory
      run: |
        # Ensure you are in the GitHub Actions workspace, which is a git repository
        cd $GITHUB_WORKSPACE

        # Check if there are any changes in the root directory after pulling from FTP
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Push changes to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        # Ensure you are in the GitHub Actions workspace, which is a git repository
        cd $GITHUB_WORKSPACE

        # Configure Git user for commit
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Stage all changes
        git add -A

        # Commit changes if there are any
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync htdocs with FTP server"
          git push origin main
        else
          echo "No changes to commit."
        fi
