name: FTP to Git Sync

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  sync_ftp_to_git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Sync files directly from FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: htdocs
        run: |
          lftp -f "
          open ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST
          mirror --continue --delete --verbose --only-newer --no-empty-dirs --exclude-glob .git/ --exclude-glob .github/ $FTP_REMOTE_DIR .
          bye
          "

      - name: Check for changes and configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          if git status --porcelain | grep -q .; then
            echo "Changes detected."
          else
            echo "No changes detected."
            exit 0
          fi

      - name: Commit and push changes
        if: ${{ success() }}
        run: |
          git add --all
          git diff-index --quiet HEAD || git commit -m "Sync from FTP server"
          git push origin main
