name: Sync FTP to GitHub

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync-ftp:
    name: Sync FTP to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main  # Checkout the main branch to perform any setup, but not used in the final commit.

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"

    - name: Generate Branch Name
      id: generate_branch
      run: |
        BRANCH_NAME="sigtax.com_$(date -d 'TZ=\"CET\"' '+%d_%m_%Y_%I_%M_%p')"
        echo "Branch name: $BRANCH_NAME"
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create Orphan Branch
      run: |
        git checkout --orphan $BRANCH_NAME
        git rm -rf . || true
        touch .gitignore
        echo ".gitignore" >> .gitignore
        git add .gitignore
        git commit -m "Initial commit on orphan branch"

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Sync with FTP server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --exclude .git/ --exclude .github/ --exclude git_action_data/ /htdocs/ ./
        "

    - name: Manage Files
      run: |
        # List local files and prepare for comparison
        find . -type f -not -path './.git/*' -not -path './.github/*' -not -name 'git_action_data/*' -exec stat --format='%Y %s %n' {} \; | sort > local_files.txt
        
        # Create the git_action_data directory and move files
        mkdir -p git_action_data
        mv local_files.txt git_action_data/
        
        # Add and commit changes
        git add git_action_data/
        git commit -m "Sync root with FTP server"

    - name: Push Changes
      run: |
        git push origin $BRANCH_NAME
