name: FTP Sync and Commit

on:
  workflow_dispatch:  # Allows the workflow to be manually triggered

jobs:
  sync_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you want to use

      - name: Install Python dependencies
        run: pip install gitpython

      - name: Run the sync and commit script
        run: python ./.github/scripts/sync_and_commit.py
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Push changes to repository
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}