name: FTP Deployment

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployment from

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP deployment tool
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp

    - name: Deploy entire repository to FTP server
      env:
        FTP_HOST: ftpupload.net
        FTP_USERNAME: if0_37166443
        FTP_PASSWORD: uc24cfJGW8ry6t
      run: |
        lftp -c "
          set ssl:verify-certificate no;
          set ftp:ssl-protect-data true;
          set ftp:ssl-force true;
          set cmd:default-protocol ftp;
          set ftp:list-options -a;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --reverse --delete --verbose --exclude-glob .git/ --exclude .github/ --no-perms ./ /remote-directory
        "
