name: Auto Merge from FTP to Git

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ftp-sync:
    name: Sync from FTP and Merge to Git
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main  # Ensure we are checking out the main branch

    - name: Verify .git directory
      run: |
        echo "Listing contents of current directory:"
        ls -la
        echo "Checking for .git directory:"
        if [ -d .git ]; then
          echo ".git directory found."
        else
          echo ".git directory not found. Exiting."
          exit 1
        fi

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Sync files from FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "Listing files from the FTP server..."
        lftp -c "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --exclude .git/ --exclude .github/ --exclude local_files.txt --exclude remote_files.txt /htdocs/ ./ftp_sync/
        "
        find ftp_sync -type f | sed 's/^\.\///' | sort > ftp_files.txt
        echo "FTP files list:"
        cat ftp_files.txt

    - name: List local files
      run: |
        find . -type f -not -path './.git/*' -not -path './.github/*' -not -name 'local_files.txt' -not -name 'ftp_files.txt' -exec sed 's/^\.\///' \; | sort > local_files.txt
        echo "Local files list:"
        cat local_files.txt

    - name: Compare and Sync Files
      run: |
        echo "Comparing file lists..."
        # List files that are on the local repository but not on the FTP server
        comm -23 local_files.txt ftp_files.txt > local_only_files.txt

        echo "Files only in local repository:"
        cat local_only_files.txt

        # Remove files from Git that are not on FTP
        while read -r file; do
          if [[ -n "$file" ]]; then
            if [ -f "$file" ]; then
              echo "Removing file: $file"
              git rm "$file" || true
            fi
          fi
        done < local_only_files.txt

    - name: Configure Git
      run: |
        echo "Configuring Git."
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git

    - name: Commit and push changes
      run: |
        git add -A
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync with FTP server"
          git push origin main
        else
          echo "No changes to commit."
        fi

    - name: Cleanup
      run: |
        rm -rf ftp_sync local_files.txt ftp_files.txt local_only_files.txt
