name: FTP to Git Sync

# Trigger this workflow manually using a dispatch event
on:
  workflow_dispatch:

jobs:
  ftp_to_git:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install curl (if not already available)
      - name: Install curl
        run: sudo apt-get install -y curl

      # Step 3: Pull data from FTP
      - name: Sync Files from FTP Server
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          curl --ftp-ssl --user "$FTP_USERNAME:$FTP_PASSWORD" ftp://$FTP_HOST/path/to/files/* -O

      # Step 4: Commit changes to the repository
      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync files from FTP server"
          git push https://x-access-token:$PAT_TOKEN@github.com/${{ github.repository }} HEAD:main
