name: FTP to Git Sync

# Trigger this workflow manually using a dispatch event
on:
  workflow_dispatch:

jobs:
  ftp_to_git:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install lftp
      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      # Step 3: Sync Files from FTP Server
      - name: Sync Files from FTP Server
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST -e "set ftp:ssl-force true; set ssl:verify-certificate no; mirror --reverse --delete --verbose / /github/workspace; quit"

      # Step 4: Commit and Push Changes to the Git Repository
      - name: Commit and Push Changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync files from FTP server"
          git push https://x-access-token:$PAT_TOKEN@github.com/${{ github.repository }} HEAD:main
