name: FTP to Git Sync

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  sync_ftp_to_git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install ftplib gitpython

      - name: Run sync script
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: python ./.github/scripts/sync_and_commit.py
