on:
  push:
    branches:
      - main  # This specifies the workflow only triggers on the main branch

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}          # FTP server address from secrets
        username: ${{ secrets.FTP_USERNAME }}    # FTP username from secrets
        password: ${{ secrets.FTP_PASSWORD }}    # FTP password from secrets
        server-dir: htdocs/                      # Specify the remote directory as 'htdocs'
