name: FTP to Git Sync

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  sync_ftp_to_git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Sync files directly from FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: htdocs
        run: |
          lftp -f "
          open ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST
          mirror --continue --delete --verbose --only-newer --no-empty-dirs --exclude-glob .git/ --exclude-glob .github/ $FTP_REMOTE_DIR .
          bye
          "

      - name: Check for changes
        run: |
          git status --porcelain | tee /tmp/git_status_output
          if [[ ! -s /tmp/git_status_output ]]; then
            echo "No changes detected."
            exit 0
          else
            echo "Changes detected."
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Sync from FTP server"
          git push origin main
        if: ${{ success() }}
