name: Manual FTP Pull

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ftp-pull:
    name: Pull from FTP and Commit to GitHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v4
      with:
        ref: dev  # Checkout the dev branch

    - name: Install FTP client
      run: sudo apt-get update && sudo apt-get install -y lftp

    - name: Generate branch name
      id: generate_branch
      run: |
        DATE=$(date -u +"sigtax.com_%d_%m_%Y_%I_%M_%p")
        echo "BRANCH_NAME=${DATE}" >> $GITHUB_ENV
        echo "Generated branch name: ${DATE}"

    - name: List local files
      run: |
        find . -type f -not -path './.git/*' -not -path './.github/*' -not -name 'files_to_keep.txt' -not -name 'ftp_files.txt' -not -name 'ftp_only_files.txt' -not -name 'git_files.txt' -not -name 'git_only_files.txt' -not -name 'local_files.txt' -not -name 'local_only_files.txt' -exec stat --format='%Y %s %n' {} \; | sort > local_files.txt
        echo "Local files list:"
        cat local_files.txt

    - name: Sync FTP files
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        echo "Listing files from the FTP server..."
        lftp -c "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --exclude .git/ --exclude .github/ --exclude files_to_keep.txt --exclude ftp_files.txt --exclude ftp_only_files.txt --exclude git_files.txt --exclude git_only_files.txt --exclude local_files.txt --exclude local_only_files.txt /htdocs/ ./
        "
        find . -type f -not -path './.git/*' -not -path './.github/*' -not -name 'files_to_keep.txt' -not -name 'ftp_files.txt' -not -name 'ftp_only_files.txt' -not -name 'git_files.txt' -not -name 'git_only_files.txt' -not -name 'local_files.txt' -not -name 'local_only_files.txt' -exec stat --format='%Y %s %n' {} \; | sort > remote_files.txt
        echo "Remote files list:"
        cat remote_files.txt

    - name: Compare and Sync Files
      run: |
        echo "Comparing local and remote files"

        # Sync files from remote to local
        while read -r remote_mod_time remote_size remote_path; do
          local_path="${remote_path}"
          local_dir=$(dirname "$local_path")

          # Skip special files
          if [[ "$local_path" == ./files_to_keep.txt || "$local_path" == ./ftp_files.txt || "$local_path" == ./ftp_only_files.txt || "$local_path" == ./git_files.txt || "$local_path" == ./git_only_files.txt || "$local_path" == ./local_files.txt || "$local_path" == ./local_only_files.txt ]]; then
            continue
          fi

          # Create the local directory if it doesn't exist
          if [ ! -d "$local_dir" ]; then
            echo "Creating directory: $local_dir"
            mkdir -p "$local_dir"
          fi

          # Check if the remote file exists
          if [ -f "$remote_path" ]; then
            if [ -f "$local_path" ]; then
              local_mod_time=$(stat --format='%Y' "$local_path")
              local_size=$(stat --format='%s' "$local_path")
              if [ "$remote_mod_time" -gt "$local_mod_time" ] || [ "$remote_size" -ne "$local_size" ]; then
                echo "Updating modified file: $local_path"
                cp "$remote_path" "$local_path"
              fi
            else
              echo "Adding new file: $local_path"
              cp "$remote_path" "$local_path"
            fi
          fi
        done < remote_files.txt

        # Remove files that are no longer in the remote directory
        while read -r local_mod_time local_size local_path; do
          if [[ "$local_path" != .git/* && "$local_path" != ./.github/* && "$local_path" != ./files_to_keep.txt && "$local_path" != ./ftp_files.txt && "$local_path" != ./ftp_only_files.txt && "$local_path" != ./git_files.txt && "$local_path" != ./git_only_files.txt && "$local_path" != ./local_files.txt && "$local_path" != ./local_only_files.txt ]]; then
            if [ ! -f "$local_path" ]; then
              echo "Removing local file not present on remote: $local_path"
              git rm "$local_path" || true
            fi
          fi
        done < local_files.txt

    - name: Configure Git
      run: |
        if [ -d .git ]; then
          echo "Configuring Git."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
        else
          echo ".git directory not found. Exiting."
          exit 1
        fi

    - name: Check for changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Create and Push to New Branch
      run: |
        # Checkout the dev branch
        git checkout dev

        # Generate a new branch name
        BRANCH_NAME=${{ env.BRANCH_NAME }}

        # Create and switch to the new branch
        git checkout -b "$BRANCH_NAME"

        # Add all changes
        git add -A
        
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync root with FTP server"
          git push origin "$BRANCH_NAME"
        else
          echo "No changes to commit."
        fi

    - name: Cleanup
      run: |
        # Remove special files after committing
        rm -f files_to_keep.txt ftp_files.txt ftp_only_files.txt git_files.txt git_only_files.txt local_files.txt local_only_files.txt
        rm -rf ftp_sync/
