name: FTP Pull and Sync

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action

jobs:
  ftp-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch the last two commits for diff comparison

    - name: Install lftp if not already installed
      run: |
        sudo apt-get update && sudo apt-get install -y lftp

    - name: Pull files from FTP server
      env:
        FTP_HOST: ftpupload.net
        FTP_USERNAME: if0_37166443
        FTP_PASSWORD: uc24cfJGW8ry6t
      run: |
        mkdir -p ftp_download
        lftp -c "
          set ssl:verify-certificate no;
          set ftp:ssl-protect-data true;
          set ftp:ssl-force true;
          set cmd:default-protocol ftp;
          set ftp:list-options -a;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror --verbose --delete --exclude-glob .git/ --exclude-glob .github/ htdocs/ ./ftp_download/
        "

    - name: Check for differences
      id: check_diff
      run: |
        cp -r ftp_download/. .
        if git diff --quiet; then
          echo "No differences detected."
          echo "::set-output name=has_changes::false"
        else
          echo "Differences detected."
          echo "::set-output name=has_changes::true"
        fi

    - name: Commit and push changes if any
      if: steps.check_diff.outputs.has_changes == 'true'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Sync with FTP server"
        git push origin main  # Push changes back to the repository
