name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger deployment from

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: 🔨 Build Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net  # Replace with your FTP server
        username: if0_37166443  # Replace with your FTP username
        password: uc24cfJGW8ry6t  # Replace with your FTP password
        local-dir: ./  # Directory to deploy from (root of repo)
        remote-dir: htdocs/  # Directory to deploy to (specified folder on remote server)
        delete: true  # Remove files on the server that no longer exist locally
