name: FTP Pull

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the pull from

jobs:
  ftp-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch the last two commits to allow diff comparison

    - name: Install FTP client
      run: |
        if ! command -v lftp &> /dev/null; then
          echo "lftp not found, installing..."
          sudo apt-get update
          sudo apt-get install -y lftp
        else
          echo "lftp is already installed"
        fi

    - name: Prepare directories for FTP operations
      run: |
        mkdir -p ftp_operations/pulled_files

    - name: Pull files from FTP server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
          set ssl:verify-certificate no;
          set ftp:ssl-protect-data true;
          set ftp:ssl-force true;
          set cmd:default-protocol ftp;
          set ftp:list-options -a;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          # Mirror command to download files to local directory
          mirror --verbose --exclude-glob .git/ --no-perms htdocs/ ftp_operations/pulled_files/
        "

    - name: List local files with sizes and modified dates
      run: |
        find ftp_operations/pulled_files -type f -exec stat --format='%Y %s %n' {} \; | sort > local_files.txt
        echo "Local files list:"
        cat local_files.txt

    - name: Compare and sync files
      run: |
        echo "Comparing and syncing files"
        while read -r remote_mod_time remote_size remote_path; do
          local_path="./$(basename "$remote_path")"
          local_dir=$(dirname "$local_path")
          echo "Processing remote file: $remote_path"
          echo "Local path: $local_path"
          mkdir -p "$local_dir"
          remote_full_path="./ftp_operations/pulled_files/$(basename "$remote_path")"
          if [ -f "$remote_full_path" ]; then
            if [ -f "$local_path" ]; then
              local_mod_time=$(stat --format='%Y' "$local_path")
              local_size=$(stat --format='%s' "$local_path")
              if [ "$remote_mod_time" -gt "$local_mod_time" ] || [ "$remote_size" -ne "$local_size" ]; then
                echo "Syncing modified file: $local_path"
                cp "$remote_full_path" "$local_path"
              fi
            else
              echo "New file detected: $local_path"
              cp "$remote_full_path" "$local_path"
            fi
          else
            echo "Remote file does not exist: $remote_full_path"
          fi
        done < local_files.txt

        # Remove files that are no longer in the FTP directory
        while read -r local_mod_time local_size local_path; do
          if [ ! -f "./ftp_operations/pulled_files/$(basename "$local_path")" ]; then
            if [ -f "$local_path" ] && [[ "$local_path" != "./local_files.txt" ]]; then
              echo "Deleting local file: $local_path"
              rm "$local_path"
            else
              echo "Local file does not exist: $local_path"
            fi
          fi
        done < local_files.txt

        # Remove files from repo that are not present in ftp_operations
        find . -type f -not -path './.git/*' -not -path './.github/*' | while read -r file; do
          if [ ! -f "./ftp_operations/pulled_files/$(basename "$file")" ]; then
            if [ -f "$file" ] && [[ "$file" != "./local_files.txt" ]]; then
              echo "Removing file from repo: $file"
              git rm "$file"
            else
              echo "File not found or is excluded: $file"
            fi
          fi
        done

    - name: Configure Git
      run: |
        if [ -d .git ]; then
          echo "Configuring Git."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git
        else
          echo ".git directory not found. Exiting."
          exit 1
        fi

    - name: Check for changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Commit and Push changes
      run: |
        git add -A
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Sync FTP directory with repository"
          git push origin main
        else
          echo "No changes to commit."
        fi

    - name: Cleanup
      run: |
        rm -rf ftp_operations
        rm -f local_files.txt  # Remove local_files.txt after use
