name: FTP Pull and Sync

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  ftp-pull:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Fetch the last two commits to allow diff comparison

    - name: Install FTP client
      run: |
        if ! command -v lftp &> /dev/null; then
          echo "lftp not found, installing..."
          sudo apt-get update
          sudo apt-get install -y lftp
        else
          echo "lftp is already installed"
        fi

    - name: Pull files from FTP server
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -c "
          set ssl:verify-certificate no;
          set ftp:ssl-protect-data true;
          set ftp:ssl-force true;
          set cmd:default-protocol ftp;
          set ftp:list-options -a;
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          # Mirror command to download files directly to the Git root directory
          mirror --verbose --exclude-glob .git/ --no-perms --parallel=10 htdocs/ ./
        "

    - name: List local files with sizes and modified dates
      run: |
        find . -type f -not -path './.git/*' -not -path './.github/*' -exec stat --format='%Y %s %n' {} \; | sort > local_files.txt
        echo "Local files list:"
        cat local_files.txt

    - name: Compare and sync files
      run: |
        echo "Comparing and syncing files"
        while read -r remote_mod_time remote_size remote_path; do
          local_path="./$(basename "$remote_path")"
          echo "Processing remote file: $remote_path"
          echo "Local path: $local_path"
          # Check if the remote file exists before attempting to copy
          remote_full_path="$remote_path"
          if [ -f "$remote_full_path" ]; then
            if [ -f "$local_path" ]; then
              local_mod_time=$(stat --format='%Y' "$local_path")
              local_size=$(stat --format='%s' "$local_path")
              if [ "$remote_mod_time" -gt "$local_mod_time" ] || [ "$remote_size" -ne "$local_size" ]; then
                echo "Replacing modified file: $local_path"
                cp "$remote_full_path" "$local_path"
              fi
            else
              echo "New file detected: $local_path"
              cp "$remote_full_path" "$local_path"
            fi
          else
            echo "Remote file does not exist: $remote_full_path"
          fi
        done < local_files.txt

    - name: Configure Git
      run: |
        if [ -d .git ]; then
          echo "Configuring Git."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ajinkyathail/htdocs.git
        else
          echo ".git directory not found. Exiting."
          exit 1
        fi

    - name: Add new and modified files to Git
      run: |
        git add -A  # Add all new and modified files to the Git index

    - name: Check for changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected. Preparing to push."
        else
          echo "No changes detected. Exiting."
          exit 0
        fi

    - name: Commit and Push changes
      run: |
        git commit -m "Sync FTP directory with repository"
        git push origin main

    - name: Cleanup
      run: |
        rm -f local_files.txt  # Remove local_files.txt after use
